#!/usr/bin/env node

/**
 * Generates vite_scripts.liquid and injects {% render 'vite_scripts', script_name: '...' %}
 * into matching section/snippet files in src. Only injects when BOTH the liquid file
 * and a corresponding src/scripts file exist.
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', 'src');
const SCRIPTS_DIR = path.join(SRC_DIR, 'scripts');
const SECTIONS_DIR = path.join(SRC_DIR, 'sections');
const SNIPPETS_DIR = path.join(SRC_DIR, 'snippets');
const SNIPPETS_OUT = path.join(SRC_DIR, 'snippets');

const VITE_SCRIPTS_RENDER = /{%\s*render\s+['"]vite_scripts['"]\s*,\s*script_name:\s*['"][^'"]+['"]\s*%}\n?/g;

function getScriptNames() {
  if (!fs.existsSync(SCRIPTS_DIR)) return [];
  return fs.readdirSync(SCRIPTS_DIR)
    .filter((f) => f.endsWith('.js'))
    .map((f) => f.replace(/\.js$/, ''));
}

function scriptNameToLiquidPath(scriptName) {
  if (scriptName.startsWith('sections_')) {
    const sectionName = scriptName.replace(/^sections_/, '');
    return { type: 'section', path: path.join(SECTIONS_DIR, `${ sectionName }.liquid`) };
  }
  if (scriptName.startsWith('snippets_')) {
    const snippetName = scriptName.replace(/^snippets_/, '');
    return { type: 'snippet', path: path.join(SNIPPETS_DIR, `${ snippetName }.liquid`) };
  }
  return null;
}

function generateViteScriptsLiquid(scriptNames) {
  const cases = scriptNames
    .map((name) => `{% when '${ name }' %}
  {% render 'vite', entry: '${ name }.js' %}`)
    .join('\n');

  return `{% comment %}
  Generated by scripts/vite-build.js – do not edit manually.
{% endcomment %}
{% case script_name %}
${ cases }
{% else %}
{% endcase %}
`;
}

function injectOrRemoveRender(content, scriptName, shouldInject) {
  const renderTag = `{% render 'vite_scripts', script_name: '${ scriptName }' %}\n`;
  const existingMatch = content.match(VITE_SCRIPTS_RENDER);

  if (shouldInject) {
    if (existingMatch && existingMatch.some((m) => m.includes(scriptName))) {
      return content;
    }
    return renderTag + content;
  }

  if (!existingMatch) return content;
  return content.replace(VITE_SCRIPTS_RENDER, (match) =>
    match.includes(scriptName) ? '' : match
  ).replace(/\n{3,}/g, '\n\n');
}

function main() {
  const scriptNames = getScriptNames();
  console.log('[vite-build] Script names:', scriptNames.join(', ') || '(none)');

  fs.mkdirSync(SNIPPETS_OUT, { recursive: true });

  const liquidPathToScriptNames = new Map();

  for (const scriptName of scriptNames) {
    const info = scriptNameToLiquidPath(scriptName);
    if (!info || !fs.existsSync(info.path)) continue;

    const key = info.path;
    if (!liquidPathToScriptNames.has(key)) {
      liquidPathToScriptNames.set(key, []);
    }
    liquidPathToScriptNames.get(key).push(scriptName);
  }

  for (const [ liquidPath, names ] of liquidPathToScriptNames) {
    let content = fs.readFileSync(liquidPath, 'utf8');
    for (const scriptName of names) {
      content = injectOrRemoveRender(content, scriptName, true);
    }
    fs.writeFileSync(liquidPath, content);
    console.log('[vite-build] Injected into', path.relative(SRC_DIR, liquidPath));
  }

  const scriptNameSet = new Set(scriptNames);
  for (const dir of [ SECTIONS_DIR, SNIPPETS_DIR ]) {
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.liquid') || f === 'vite_scripts.liquid') continue;
      const p = path.join(dir, f);
      let content = fs.readFileSync(p, 'utf8');
      const matches = content.matchAll(/{%\s*render\s+['"]vite_scripts['"]\s*,\s*script_name:\s*['"]([^'"]+)['"]\s*%}\n?/g);
      for (const m of matches) {
        const injectedName = m[1];
        if (!scriptNameSet.has(injectedName)) {
          content = injectOrRemoveRender(content, injectedName, false);
          fs.writeFileSync(p, content);
          console.log('[vite-build] Removed', injectedName, 'from', path.relative(SRC_DIR, p));
        }
      }
    }
  }

  const viteScriptsPath = path.join(SNIPPETS_OUT, 'vite_scripts.liquid');
  fs.writeFileSync(viteScriptsPath, generateViteScriptsLiquid(scriptNames));
  console.log('[vite-build] Generated', path.relative(SRC_DIR, viteScriptsPath));
}

main();
