#!/usr/bin/env node

/**
 * Reads Vite manifest, generates vite_scripts.liquid with script/stylesheet tags,
 * and injects into matching section/snippet files. Pairs scripts with liquid by name:
 * ProductTile.js, product_tile.js, productTile.js → snippets/product_tile.liquid
 * Product.js, product.js → sections/product.liquid
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', 'src');
const SCRIPTS_DIR = path.join(SRC_DIR, 'scripts');
const SECTIONS_DIR = path.join(SRC_DIR, 'sections');
const SNIPPETS_DIR = path.join(SRC_DIR, 'snippets');
const BUILD_DIR = path.join(__dirname, '..', 'build', 'assets');
const MANIFEST_PATH = path.join(BUILD_DIR, '.vite', 'manifest.json');

const VITE_SCRIPTS_RENDER = /{%\s*render\s+['"]vite_scripts['"]\s*,\s*script_name:\s*['"][^'"]+['"]\s*%}\n?/g;

function camelToSnake(str) {
  return str
    .replace(/([A-Z])/g, (m) => `_${ m.toLowerCase() }`)
    .replace(/^_/, '')
    .replace(/-/g, '_');
}

function normalizeScriptName(filename) {
  return camelToSnake(filename.replace(/\.(js|css)$/, ''));
}

function findLiquidPath(normalizedName) {
  let base = normalizedName;
  if (base.startsWith('sections_')) {
    base = base.replace(/^sections_/, '');
    return fs.existsSync(path.join(SECTIONS_DIR, `${ base }.liquid`))
      ? path.join(SECTIONS_DIR, `${ base }.liquid`)
      : null;
  }
  if (base.startsWith('snippets_')) {
    base = base.replace(/^snippets_/, '');
    return fs.existsSync(path.join(SNIPPETS_DIR, `${ base }.liquid`))
      ? path.join(SNIPPETS_DIR, `${ base }.liquid`)
      : null;
  }
  const candidates = [
    path.join(SECTIONS_DIR, `${ base }.liquid`),
    path.join(SNIPPETS_DIR, `${ base }.liquid`),
  ];
  return candidates.find((p) => fs.existsSync(p)) || null;
}

function getManifestEntries() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error('Manifest not found. Run vite build first.');
  }
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  const entries = [];
  for (const [ key, val ] of Object.entries(manifest)) {
    if (!val.isEntry) continue;
    const name = val.name || path.basename(key, path.extname(key));
    const normalizedKey = normalizeScriptName(name);
    const file = path.basename(val.file);
    entries.push({
      key: normalizedKey,
      name,
      file,
      isCss: /\.(css|scss|sass)$/i.test(key),
    });
  }
  return entries;
}

function generateViteScriptsLiquid(entries) {
  const cases = entries.map((e) => {
    const tag = e.isCss
      ? `{{ '${ e.file }' | asset_url | split: '?' | first | stylesheet_tag: preload: preload_stylesheet }}`
      : `<script src="{{ '${ e.file }' | asset_url | split: '?' | first }}" type="module" crossorigin="anonymous"></script>`;
    return `{% when '${ e.key }' %}\n  ${ tag }`;
  });

  return `{% comment %}
  Generated by scripts/vite-build.js – do not edit manually.
{% endcomment %}
{% case script_name %}
${ cases.join('\n') }
{% else %}
{% endcase %}
`;
}

function injectOrRemoveRender(content, scriptKey, shouldInject) {
  const renderTag = `{% render 'vite_scripts', script_name: '${ scriptKey }' %}\n`;
  const existingMatch = content.match(VITE_SCRIPTS_RENDER);

  if (shouldInject) {
    if (existingMatch && existingMatch.some((m) => m.includes(scriptKey))) return content;
    return renderTag + content;
  }
  if (!existingMatch) return content;
  return content
    .replace(VITE_SCRIPTS_RENDER, (match) => (match.includes(scriptKey) ? '' : match))
    .replace(/\n{3,}/g, '\n\n');
}

function main() {
  const entries = getManifestEntries();
  console.log('[vite-build] Entries:', entries.map((e) => e.key).join(', ') || '(none)');

  fs.mkdirSync(SNIPPETS_DIR, { recursive: true });

  const liquidToKeys = new Map();
  for (const e of entries) {
    const liquidPath = findLiquidPath(e.key);
    if (!liquidPath) continue;
    if (!liquidToKeys.has(liquidPath)) liquidToKeys.set(liquidPath, []);
    liquidToKeys.get(liquidPath).push(e.key);
  }

  for (const [ liquidPath, keys ] of liquidToKeys) {
    let content = fs.readFileSync(liquidPath, 'utf8');
    for (const key of keys) {
      content = injectOrRemoveRender(content, key, true);
    }
    fs.writeFileSync(liquidPath, content);
    console.log('[vite-build] Injected into', path.relative(SRC_DIR, liquidPath));
  }

  const entryKeys = new Set(entries.map((e) => e.key));
  for (const dir of [ SECTIONS_DIR, SNIPPETS_DIR ]) {
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.liquid') || f === 'vite_scripts.liquid') continue;
      const p = path.join(dir, f);
      let content = fs.readFileSync(p, 'utf8');
      const matches = [ ...content.matchAll(/{%\s*render\s+['"]vite_scripts['"]\s*,\s*script_name:\s*['"]([^'"]+)['"]\s*%}\n?/g) ];
      for (const m of matches) {
        const key = m[1];
        if (!entryKeys.has(key)) {
          content = injectOrRemoveRender(content, key, false);
          fs.writeFileSync(p, content);
          console.log('[vite-build] Removed', key, 'from', path.relative(SRC_DIR, p));
        }
      }
    }
  }

  const allKeys = entries.map((e) => e.key);
  const viteScriptsPath = path.join(SNIPPETS_DIR, 'vite_scripts.liquid');
  fs.writeFileSync(viteScriptsPath, generateViteScriptsLiquid(entries));
  console.log('[vite-build] Generated', path.relative(SRC_DIR, viteScriptsPath));
}

main();
